---
# Source: kubeblocks/templates/addons/milvus-addon.yaml
apiVersion: extensions.kubeblocks.io/v1alpha1
kind: Addon
metadata:
  name: milvus
  labels:
    app.kubernetes.io/name: kubeblocks
    app.kubernetes.io/instance: release-name
    addon.kubeblocks.io/version: 2.3.2
    addon.kubeblocks.io/name: milvus
    addon.kubeblocks.io/provider: community
    addon.kubeblocks.io/model: vector
  annotations:
    addon.kubeblocks.io/kubeblocks-version: '>=0.7.0'
spec:
  description: 'Milvus is an open source (Apache-2.0 licensed) vector database built to power embedding similarity search and AI applications.'
  type: Helm
  helm:    
    chartLocationURL: file:///milvus-2.3.2.tgz
    chartsImage: infracreate-registry.cn-zhangjiakou.cr.aliyuncs.com/apecloud/kubeblocks-charts:0.8.1
    chartsPathInImage: /charts
    installOptions:
  defaultInstallValues:
  - enabled: true
  installable:
    autoInstall: false
