---
# Source: kubeblocks/templates/addons/oceanbase-addon.yaml
apiVersion: extensions.kubeblocks.io/v1alpha1
kind: Addon
metadata:
  name: oceanbase
  labels:
    app.kubernetes.io/name: kubeblocks
    app.kubernetes.io/instance: release-name
    addon.kubeblocks.io/version: 0.8.1
    addon.kubeblocks.io/name: oceanbase
    addon.kubeblocks.io/provider: community
    addon.kubeblocks.io/model: RDBMS
  annotations:
    addon.kubeblocks.io/kubeblocks-version: '>=0.8.0'
spec:
  description: 'OceanBase Database is an enterprise-level native distributed database independently developed by Ant Group.'
  type: Helm
  helm:    
    chartLocationURL: file:///oceanbase-0.8.1.tgz
    chartsImage: infracreate-registry.cn-zhangjiakou.cr.aliyuncs.com/apecloud/kubeblocks-charts:0.8.1
    chartsPathInImage: /charts
    installOptions:
  defaultInstallValues:
  - enabled: true
  installable:
    autoInstall: false
