---
# Source: kubeblocks/templates/applications/bytebase-addon.yaml
apiVersion: extensions.kubeblocks.io/v1alpha1
kind: Addon
metadata:
  name: bytebase
  labels:
    helm.sh/chart: kubeblocks-0.8.1
    app.kubernetes.io/name: kubeblocks
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.8.1"
    app.kubernetes.io/managed-by: Helm
    "addon.kubeblocks.io/provider": community
    "addon.kubeblocks.io/version": "0.7.0"
spec:
  description: 'Bytebase is Database DevOps and CI/CD for Developer, DBA and Platform Engineering team.'
  type: Helm

  helm:    
    chartLocationURL: file:///bytebase-0.7.0.tgz    
    chartsImage: infracreate-registry.cn-zhangjiakou.cr.aliyuncs.com/apecloud/kubeblocks-charts:0.8.1
    chartsPathInImage: /charts
    installOptions:

  installable:
    autoInstall: false

  defaultInstallValues:
  - enabled: true
