---
# Source: kubeblocks/templates/applications/csi-driver-addon.yaml
apiVersion: extensions.kubeblocks.io/v1alpha1
kind: Addon
metadata:
  name: kubeblocks-csi-driver
  labels:
    helm.sh/chart: kubeblocks-0.8.1
    app.kubernetes.io/name: kubeblocks
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.8.1"
    app.kubernetes.io/managed-by: Helm
    "addon.kubeblocks.io/provider": community
    "addon.kubeblocks.io/version": "0.1.4"
spec:
  description: 'KubeBlocks CSI driver provides a container storage interface used by Container Orchestrators
    to manage the lifecycle of block storage for cloud vendors.'
  type: Helm

  helm:    
    chartLocationURL: file:///kubeblocks-csi-driver-0.1.4.tgz    
    chartsImage: infracreate-registry.cn-zhangjiakou.cr.aliyuncs.com/apecloud/kubeblocks-charts:0.8.1
    chartsPathInImage: /charts

    installOptions:

    valuesMapping:
      valueMap:
        replicaCount: controller.replicaCount
      jsonMap:
        tolerations: controller.tolerations

      resources:
        cpu:
          requests: controller.resources.requests.cpu
          limits: controller.resources.limits.cpu
        memory:
          requests: controller.resources.requests.memory
          limits: controller.resources.limits.memory
      extras:
        - name: node
          jsonMap:
            tolerations: node.tolerations

          resources:
            cpu:
              requests: node.resources.requests.cpu
              limits: node.resources.limits.cpu
            memory:
              requests: node.resources.requests.memory
              limits: node.resources.limits.memory

  defaultInstallValues:
    - enabled: false
      tolerations: "[{\"effect\":\"NoSchedule\",\"key\":\"kb-controller\",\"operator\":\"Equal\",\"value\":\"true\"}]"
      extras:
        - name: node
          tolerations: "[{\"effect\":\"NoSchedule\",\"key\":\"kb-controller\",\"operator\":\"Equal\",\"value\":\"true\"}]"


  installable:
    autoInstall: false
    selectors:
      - key: KubeGitVersion
        operator: Contains
        values:
          - eks
