---
# Source: kubeblocks/templates/applications/jupyterhub-addon.yaml
apiVersion: extensions.kubeblocks.io/v1alpha1
kind: Addon
metadata:
  name: jupyter-hub
  labels:
    helm.sh/chart: kubeblocks-0.8.1
    app.kubernetes.io/name: kubeblocks
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.8.1"
    app.kubernetes.io/managed-by: Helm
    "addon.kubeblocks.io/provider": community
    "addon.kubeblocks.io/version": "0.1.0"
spec:
  description: 'JupyterHub is a multi-user platform for hosting Jupyter Notebooks.'
  type: Helm

  helm:    
    chartLocationURL: file:///jupyterhub-0.1.0.tgz    
    chartsImage: infracreate-registry.cn-zhangjiakou.cr.aliyuncs.com/apecloud/kubeblocks-charts:0.8.1
    chartsPathInImage: /charts

    installOptions:

  installable:
    autoInstall: false

  defaultInstallValues:
    - enabled: true
