---
# Source: kubeblocks/templates/applications/migration-addon.yaml
apiVersion: extensions.kubeblocks.io/v1alpha1
kind: Addon
metadata:
  name: migration
  labels:
    helm.sh/chart: kubeblocks-0.8.1
    app.kubernetes.io/name: kubeblocks
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.8.1"
    app.kubernetes.io/managed-by: Helm
    "addon.kubeblocks.io/provider": apecloud
    "addon.kubeblocks.io/version": "0.1.1"
spec:
  description: 'Migration is a tool for migrating data between two databases.'

  type: Helm

  helm:    
    chartLocationURL: file:///dt-platform-0.1.1.tgz    
    chartsImage: infracreate-registry.cn-zhangjiakou.cr.aliyuncs.com/apecloud/kubeblocks-charts:0.8.1
    chartsPathInImage: /charts

    installOptions:

    valuesMapping:
      valueMap:
        replicaCount: replicaCount

      jsonMap:
        tolerations: tolerations

      resources:
        cpu:
          requests: resources.requests.cpu
          limits: resources.limits.cpu
        memory:
          requests: resources.requests.memory
          limits: resources.limits.memory

  installable:
    autoInstall: false

  defaultInstallValues:
    - enabled: true
      tolerations: "[{\"effect\":\"NoSchedule\",\"key\":\"kb-controller\",\"operator\":\"Equal\",\"value\":\"true\"}]"
